export type OpenApiRoute = {
  method: "get" | "post" | "patch" | "delete";
  path: string;
  operationId: string;
  auth?: "bearer" | "cookie";
  body?: string;
  query?: string[];
  params?: string[];
  response?: "created" | "redirect" | "file";
};

export const openApiRoutes: OpenApiRoute[] = [
  { method: "get", path: "/health", operationId: "health" },
  { method: "post", path: "/auth/register", operationId: "register", body: "Register" },
  { method: "post", path: "/auth/login", operationId: "login", body: "Login" },
  { method: "post", path: "/auth/logout", operationId: "logout", auth: "cookie" },
  { method: "post", path: "/auth/refresh", operationId: "refresh", auth: "cookie" },
  { method: "get", path: "/auth/me", operationId: "getCurrentUser", auth: "bearer" },
  { method: "post", path: "/auth/verify-email", operationId: "verifyEmail", body: "Token" },
  {
    method: "post",
    path: "/auth/resend-verification",
    operationId: "resendVerification",
    body: "Email",
  },
  { method: "post", path: "/auth/forgot-password", operationId: "forgotPassword", body: "Email" },
  {
    method: "post",
    path: "/auth/reset-password",
    operationId: "resetPassword",
    body: "ResetPassword",
  },
  {
    method: "patch",
    path: "/auth/change-password",
    operationId: "changePassword",
    auth: "bearer",
    body: "ChangePassword",
  },
  {
    method: "post",
    path: "/auth/set-password",
    operationId: "setPassword",
    auth: "bearer",
    body: "SetPassword",
  },
  {
    method: "get",
    path: "/auth/connected-accounts",
    operationId: "listConnectedAccounts",
    auth: "bearer",
  },
  {
    method: "post",
    path: "/auth/connected-accounts/{provider}/link",
    operationId: "linkConnectedAccount",
    auth: "bearer",
    params: ["provider"],
  },
  {
    method: "delete",
    path: "/auth/connected-accounts/{provider}",
    operationId: "unlinkConnectedAccount",
    auth: "bearer",
    params: ["provider"],
  },
  { method: "get", path: "/auth/google", operationId: "startGoogleOAuth", response: "redirect" },
  {
    method: "get",
    path: "/auth/google/callback",
    operationId: "completeGoogleOAuth",
    response: "redirect",
    query: ["code", "state"],
  },
  { method: "get", path: "/auth/github", operationId: "startGitHubOAuth", response: "redirect" },
  {
    method: "get",
    path: "/auth/github/callback",
    operationId: "completeGitHubOAuth",
    response: "redirect",
    query: ["code", "state"],
  },
  {
    method: "patch",
    path: "/users/me/profile",
    operationId: "updateProfile",
    auth: "bearer",
    body: "Profile",
  },
  {
    method: "patch",
    path: "/users/me/preferences",
    operationId: "updatePreferences",
    auth: "bearer",
    body: "Preferences",
  },
  {
    method: "get",
    path: "/applications",
    operationId: "listApplications",
    auth: "bearer",
    query: [
      "page",
      "pageSize",
      "search",
      "status",
      "tag",
      "remoteType",
      "employmentType",
      "source",
      "appliedFrom",
      "appliedTo",
      "followUp",
      "includeArchived",
      "sort",
      "order",
    ],
  },
  {
    method: "post",
    path: "/applications",
    operationId: "createApplication",
    auth: "bearer",
    body: "CreateApplication",
    response: "created",
  },
  {
    method: "get",
    path: "/applications/{id}",
    operationId: "getApplication",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "patch",
    path: "/applications/{id}",
    operationId: "updateApplication",
    auth: "bearer",
    params: ["id"],
    body: "UpdateApplication",
  },
  {
    method: "delete",
    path: "/applications/{id}",
    operationId: "deleteApplication",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "post",
    path: "/applications/{id}/archive",
    operationId: "archiveApplication",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "post",
    path: "/applications/{id}/unarchive",
    operationId: "unarchiveApplication",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "post",
    path: "/applications/{id}/status",
    operationId: "changeApplicationStatus",
    auth: "bearer",
    params: ["id"],
    body: "ChangeStatus",
  },
  {
    method: "get",
    path: "/applications/{id}/history",
    operationId: "getApplicationHistory",
    auth: "bearer",
    params: ["id"],
  },
  { method: "get", path: "/tags", operationId: "listTags", auth: "bearer" },
  {
    method: "post",
    path: "/tags",
    operationId: "createTag",
    auth: "bearer",
    body: "CreateTag",
    response: "created",
  },
  {
    method: "patch",
    path: "/tags/{id}",
    operationId: "updateTag",
    auth: "bearer",
    params: ["id"],
    body: "UpdateTag",
  },
  {
    method: "delete",
    path: "/tags/{id}",
    operationId: "deleteTag",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "post",
    path: "/applications/{id}/tags",
    operationId: "addApplicationTags",
    auth: "bearer",
    params: ["id"],
    body: "AddTags",
  },
  {
    method: "delete",
    path: "/applications/{id}/tags/{tagId}",
    operationId: "removeApplicationTag",
    auth: "bearer",
    params: ["id", "tagId"],
  },
  {
    method: "get",
    path: "/applications/{id}/notes",
    operationId: "listApplicationNotes",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "post",
    path: "/applications/{id}/notes",
    operationId: "createNote",
    auth: "bearer",
    params: ["id"],
    body: "Note",
    response: "created",
  },
  {
    method: "patch",
    path: "/notes/{id}",
    operationId: "updateNote",
    auth: "bearer",
    params: ["id"],
    body: "Note",
  },
  {
    method: "delete",
    path: "/notes/{id}",
    operationId: "deleteNote",
    auth: "bearer",
    params: ["id"],
  },
  {
    method: "get",
    path: "/interviews",
    operationId: "listInterviews",
    auth: "bearer",
    query: ["range", "page", "pageSize", "includeArchived"],
  },
  {
    method: "get",
    path: "/applications/{id}/interviews",
    operationId: "listApplicationInterviews",
    auth: "bearer",
    params: ["id"],
    query: ["range", "page", "pageSize", "includeArchived"],
  },
  {
    method: "post",
    path: "/applications/{id}/interviews",
    operationId: "createInterview",
    auth: "bearer",
    params: ["id"],
    body: "CreateInterview",
    response: "created",
  },
  {
    method: "patch",
    path: "/interviews/{id}",
    operationId: "updateInterview",
    auth: "bearer",
    params: ["id"],
    body: "UpdateInterview",
  },
  {
    method: "delete",
    path: "/interviews/{id}",
    operationId: "deleteInterview",
    auth: "bearer",
    params: ["id"],
  },
  { method: "get", path: "/dashboard", operationId: "getDashboard", auth: "bearer" },
  {
    method: "get",
    path: "/export/json",
    operationId: "exportJson",
    auth: "bearer",
    response: "file",
  },
  {
    method: "get",
    path: "/export/csv",
    operationId: "exportCsv",
    auth: "bearer",
    response: "file",
  },
  {
    method: "post",
    path: "/import/json",
    operationId: "importJson",
    auth: "bearer",
    body: "ImportBackup",
  },
];
